// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd4zzUIDEVfKrGYLIubqvWkkEod2DGwDc',
    appId: '1:584681060534:web:ccce8793938ec5cbe04e17',
    messagingSenderId: '584681060534',
    projectId: 'lingobreeze-a5993',
    authDomain: 'lingobreeze-a5993.firebaseapp.com',
    storageBucket: 'lingobreeze-a5993.firebasestorage.app',
    measurementId: 'G-1B5P2NCHJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkML_yerY9KuiUV7Bic4wlhmvHlFQZUcc',
    appId: '1:584681060534:android:7bde8e08e28d171be04e17',
    messagingSenderId: '584681060534',
    projectId: 'lingobreeze-a5993',
    storageBucket: 'lingobreeze-a5993.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDccYqgBJZaWLecZumwSu4riMdt2TqKBWA',
    appId: '1:584681060534:ios:233ce9f70d86de97e04e17',
    messagingSenderId: '584681060534',
    projectId: 'lingobreeze-a5993',
    storageBucket: 'lingobreeze-a5993.firebasestorage.app',
    iosBundleId: 'com.example.lingoBreeze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDccYqgBJZaWLecZumwSu4riMdt2TqKBWA',
    appId: '1:584681060534:ios:233ce9f70d86de97e04e17',
    messagingSenderId: '584681060534',
    projectId: 'lingobreeze-a5993',
    storageBucket: 'lingobreeze-a5993.firebasestorage.app',
    iosBundleId: 'com.example.lingoBreeze',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd4zzUIDEVfKrGYLIubqvWkkEod2DGwDc',
    appId: '1:584681060534:web:46788563ccf51b9fe04e17',
    messagingSenderId: '584681060534',
    projectId: 'lingobreeze-a5993',
    authDomain: 'lingobreeze-a5993.firebaseapp.com',
    storageBucket: 'lingobreeze-a5993.firebasestorage.app',
    measurementId: 'G-Y118NGF8H2',
  );
}
